### ISSUE TITLE
Midterm Project Presentation - Technical Overview

### ISSUE THREAD

**Issue by baonhivu** [COMP-523-Sustainability-Tracker/sustainability-tracker#8]
**Prompt:**
Since almost all projects are very early in code development, this section will mainly be a presentation and explanation of your architecture diagram. Feel free to include any supporting details from the design of subsystems that you might have, but we are looking in this presentation for a high-level structure. Technical details will be a larger component of your final presentation at the end of the semester.

**Acceptance Criteria:**
- 1.5 minutes of content
- Does not include a demo
- Does not have paragraphs of words
- Updated architecture diagram

**Presentation:**
[Link](https://docs.google.com/presentation/d/1YT305-lgY5gy72ajolNfe_15K255XB38yN7eIeYbdZg/edit#slide=id.p)

**Comment by StevenAMartin** [comment]
We are done with this
